### ISSUE TITLE
panic: Unexpected error from context packet: context deadline exceeded

### ISSUE THREAD

**Issue by gyuho** [coreos/dbtester#245]
```
2017-02-03 22:51:39.543127 I | control: step 3: stopping databases...
2017-02-03 22:51:39.543264 I | control: sending message [index: 0 | operation: "Stop" | database: "etcdv3" | endpoint: "10.240.0.20:3500"]
2017-02-03 22:51:40.543563 I | control: sending message [index: 1 | operation: "Stop" | database: "etcdv3" | endpoint: "10.240.0.21:3500"]
2017-02-03 22:51:41.543750 I | control: sending message [index: 2 | operation: "Stop" | database: "etcdv3" | endpoint: "10.240.0.22:3500"]
2017-02-03 22:51:50.337145 I | control: got response [index: 0 | endpoint: "10.240.0.20:3500" | response: success:true datasize:2840425696 ]
2017-02-03 22:51:50.885129 I | control: got response [index: 1 | endpoint: "10.240.0.21:3500" | response: success:true datasize:2852999600 ]
panic: Unexpected error from context packet: context deadline exceeded

goroutine 32325 [running]:
panic(0xd527e0, 0xc4283a2450)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/coreos/dbtester/vendor/google.golang.org/grpc/transport.ContextErr(0x13ad980, 0x1638c98, 0x1638c98, 0x1, 0x0)
	/home/gyuho/go/src/github.com/coreos/dbtester/vendor/google.golang.org/grpc/transport/transport.go:566 +0x213
github.com/coreos/dbtester/vendor/google.golang.org/grpc/transport.(*Stream).Header(0xc42025a4b0, 0xf73720, 0xc42e933a70, 0x13bb860)
	/home/gyuho/go/src/github.com/coreos/dbtester/vendor/google.golang.org/grpc/transport/transport.go:241 +0x11a
github.com/coreos/dbtester/vendor/google.golang.org/grpc.recvResponse(0x0, 0x0, 0x13b7c00, 0x1638c98, 0x0, 0x0, 0x0, 0x0, 0x13aee00, 0xc42b552640, ...)
	/home/gyuho/go/src/github.com/coreos/dbtester/vendor/google.golang.org/grpc/call.go:61 +0xaa
github.com/coreos/dbtester/vendor/google.golang.org/grpc.invoke(0x7f1dd3a03218, 0xc42be7d440, 0xf07f1c, 0x1d, 0xe45d20, 0xc42cc66000, 0xe45e00, 0xc4283a23d0, 0xc42033e900, 0x0, ...)
	/home/gyuho/go/src/github.com/coreos/dbtester/vendor/google.golang.org/grpc/call.go:208 +0x8a1
github.com/coreos/dbtester/vendor/google.golang.org/grpc.Invoke(0x7f1dd3a03218, 0xc42be7d440, 0xf07f1c, 0x1d, 0xe45d20, 0xc42cc66000, 0xe45e00, 0xc4283a23d0, 0xc42033e900, 0x0, ...)
	/home/gyuho/go/src/github.com/coreos/dbtester/vendor/google.golang.org/grpc/call.go:118 +0x19c
github.com/coreos/dbtester/agent/agentpb.(*transporterClient).Transfer(0xc42e1de0d8, 0x7f1dd3a03218, 0xc42be7d440, 0xc42cc66000, 0x0, 0x0, 0x0, 0x0, 0xc426e1c0f8, 0x9)
	/home/gyuho/go/src/github.com/coreos/dbtester/agent/agentpb/message.pb.go:183 +0xd2
github.com/coreos/dbtester/control.sendReq(0xc42013bd00, 0x10, 0x100000001, 0xc4201695c0, 0x27, 0x0, 0xc4201450e0, 0x11, 0x0, 0x186a0, ...)
	/home/gyuho/go/src/github.com/coreos/dbtester/control/step1_start_database.go:79 +0x55f
github.com/coreos/dbtester/control.bcastReq.func1(0xc420164200, 0xc4200ca000, 0xc42f5d6e40, 0xc42f5d6de0, 0x2)
	/home/gyuho/go/src/github.com/coreos/dbtester/control/step1_start_database.go:36 +0xa5
created by github.com/coreos/dbtester/control.bcastReq
	/home/gyuho/go/src/github.com/coreos/dbtester/control/step1_start_database.go:41 +0x1df
```

**Comment by gyuho** [comment]
```
2017-02-03 22:51:47.551742 I | agent: upload signal received; saving CSV at "/home/gyuho/system-metrics.csv"
2017-02-03 22:51:47.557469 I | agent: CSV saved at "/home/gyuho/system-metrics.csv"
2017-02-03 22:51:47.592697 I | agent: CSV saved at "/home/gyuho/system-metrics-interpolated.csv"
2017-02-03 22:51:47.592730 I | agent: stopped collecting metrics; uploading logs to storage "etcd-development"
2017-02-03 22:51:47.592895 I | agent: uploading database log ["/home/gyuho/database.log" -> "2017Q1-02-etcd-zookeeper-consul/01-write-1M-keys-client-variable/etcd-v3.1-go1.7.4-3-database.log"]
2017-02-03 22:51:48.395598 I | remotestorage: uploading "/home/gyuho/database.log" ---> "2017Q1-02-etcd-zookeeper-consul/01-write-1M-keys-client-variable/etcd-v3.1-go1.7.4-3-database.log"
2017-02-03 22:51:48.633653 I | remotestorage: finished uploading "/home/gyuho/database.log"
2017-02-03 22:51:48.633738 I | agent: uploading system metrics data ["/home/gyuho/system-metrics.csv" -> "2017Q1-02-etcd-zookeeper-consul/01-write-1M-keys-client-variable/etcd-v3.1-go1.7.4-3-system-metrics.csv"]
2017-02-03 22:51:49.441899 I | remotestorage: uploading "/home/gyuho/system-metrics.csv" ---> "2017Q1-02-etcd-zookeeper-consul/01-write-1M-keys-client-variable/etcd-v3.1-go1.7.4-3-system-metrics.csv"
2017-02-03 22:51:49.750763 I | remotestorage: finished uploading "/home/gyuho/system-metrics.csv"
2017-02-03 22:51:49.750807 I | agent: uploading system metrics interpolated data ["/home/gyuho/system-metrics-interpolated.csv" -> "2017Q1-02-etcd-zookeeper-consul/01-write-1M-keys-client-variable/etcd-v3.1-go1.7.4-3-system-metrics-interpolated.csv"]
2017-02-03 22:52:06.584878 I | remotestorage: uploading "/home/gyuho/system-metrics-interpolated.csv" ---> "2017Q1-02-etcd-zookeeper-consul/01-write-1M-keys-client-variable/etcd-v3.1-go1.7.4-3-system-metrics-interpolated.csv"
2017-02-03 22:52:06.957609 I | remotestorage: finished uploading "/home/gyuho/system-metrics-interpolated.csv"
2017-02-03 22:52:06.957651 I | agent: uploading agent logs ["/home/gyuho/agent.log" -> "2017Q1-02-etcd-zookeeper-consul/01-write-1M-keys-client-variable/etcd-v3.1-go1.7.4-3-agent.log"]
2017-02-03 22:52:07.992588 I | remotestorage: uploading "/home/gyuho/agent.log" ---> "2017Q1-02-etcd-zookeeper-consul/01-write-1M-keys-client-variable/etcd-v3.1-go1.7.4-3-agent.log"
2017-02-03 22:52:08.233964 I | remotestorage: finished uploading "/home/gyuho/agent.log"
2017-02-03 22:52:08.234231 I | agent: Transfer success!
```

agent was taking awhile to finish uploads. Will just bump up the timeout.
